server:
   port: 8080

spring:
   profiles:
      include: easecurity   # 加载配置文件
   application:
      name: gateway
   cloud:
      zookeeper:
         connect-string: 128.0.0.2:2181
         discovery:
            enabled: true
            register: true
      gateway:
         routes: #数组形式
           - id: serviceServer  #路由唯一标识
             uri: lb://serviceServer  #想要转发到的地址
             order: 1 #优先级，数字越小优先级越高
             predicates: #断言 配置哪个路径才转发
               - Path=/**
#             filters: #过滤器，请求在传递过程中通过过滤器修改
#               - StripPrefix=1  #去掉第一层前缀

    
# 缓存配置
   redis:
      host: 128.0.0.2
      port: 16379
#      password: 123456
      database: 0
#      coredatabase: 2
      timeout: 3000
      lettuce:
         pool:
            max-wait: 1000  # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接 抛出JedisConnectionException
            max-active: 5   # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool 的状态为exhausted(耗尽)
            max-idle: 1     # 连接池中的最大空闲连接，默认值也是8。
            min-idle: 1     # 连接池中的最小空闲连接，默认值也是0。
         shutdown-timeout: 10000ms  # 关闭超时时间
#         host: 128.0.0.1
#         port: 16379
#         password: 123456
#         database: 0
#         timeout: 3000
# 设置Redis序列化类。对于稳定的生产系统，建议选用最快速的序列化类；对于开发或者刚上线的系统，建议选用易解读的序列化类。
# 目前支持常见的RedisTemplate类。包括：
# 支持自定义，自定义类需要实现com.easecurity.core.redis.OemRedisSerializer接口
      serializer:
         key: StringRedisSerializer
#         value: Jackson2JsonRedisSerializer
         value: Jackson2JsonRedisSerializer
         hashkey: StringRedisSerializer
         hashvalue: GenericJackson2JsonRedisSerializer

logging:
   level:
      root: INFO
      com:
         easecurity: DEBUG
   pattern:
      console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){faint}%clr([%F:%L]){cyan} %clr(:){faint} %m%n%wex'

