---
# 企业安全中心相关配置
easecurity:
   cache:
      user:
         validTime: 3600   # 有效期。单位秒
   client:
      ips: 128.0.0.1,128.0.0.2,127.0.0.1
      logout:
         url: http://128.0.0.1:8080/demo/logout,http://128.0.0.2/demo/logout
   refresh_token:
      validTime: 6048001   # 有效期。单位秒
   # jwt配置
   jwt:
      validTime: 3600   # 有效期。单位秒
      privateKey: classpath:app.key
      publicKey: classpath:app.pub

---
# 登录验证码
loginCaptcha:
    disable: false    # 禁用验证码
    type: gifCaptcha  # 验证码类型，目前只支持图片验证码
    gifCaptcha:
        length: 5    # 验证码字符个数
        delay: 200   # 验证码闪烁时间间隔
        validTime: 300000   # 验证码有效时间（毫秒）


         