---
server:
    port: 8080
    servlet:
        context-path: /admin
---
grails:
    profile: web
    codegen:
        defaultPackage: com.easecurity
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    profiles:
        include: easecurity
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
environments:
    development:
        management:
            endpoints:
                enabled-by-default: true
                web:
                    base-path: '/actuator'
                    exposure:
                        include: '*'
    production:
        management:
            endpoints:
                enabled-by-default: false
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
---
hibernate:
# if false, uses the Grails DirtyCheckable; if true, uses Hibernate checking.
# if true, The implementation modifies all setters of your class so that dirty checking is tracked per field. However, there is
# one corner case where you do name = "blah" in a method internal to the class, the setter will not be called and
# property will not be marked as dirty. Hence, changing it to setName("blah") resolves the issue.
    hibernateDirtyChecking: true
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.cj.jdbc.Driver
#    autocommit: true
#    logSql: true

environments:
    development:
        dataSource:
            dbCreate: create-drop
#            url: jdbc:mysql://127.0.0.1:3306/easecurity?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8
            url: jdbc:mysql://127.0.0.1:3306/easecurity?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF8
            username: easuser
            password: easuser
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            driverClassName: org.h2.Driver
            username: sa
            password: ''
    production:
        dataSource:
            dbCreate: none
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            driverClassName: org.h2.Driver
            username: sa
            password: ''
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
#开发gsp模板时，可以打开，取消缓存
#grails:
#    plugin:
#        fields:
#            disableLookupCache: true

---
logging:
    #   file:
    #      path: logs
    #      max-size: 100MB
    #      max-history: 20
    level:
        root: INFO
        com:
            easecurity: DEBUG
    pattern:
        console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5p)--%clr([%.12t]){faint} %c{50}%clr([%F:%L]){cyan}: %m%n%wex'
#      file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5p)--%clr([%thread]){faint} %clr(%c){faint}%clr([%F:%L]){cyan}: %m%n%wex'
